FROM ubuntu:18.04

LABEL mainteiner="Adaão - armascarelli@gmail.com"

RUN apt-get update && apt-get install curl net-tools -y

RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

